# Generated by Django 3.1.12 on 2025-05-27 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('randevu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='event',
        ),
        migrations.AddField(
            model_name='appointment',
            name='category',
            field=models.CharField(choices=[('danismanlik', 'Danışmanlık'), ('saglik', 'Sağlık'), ('gorusme', 'Görüşme'), ('mulakat', 'Mülakat'), ('diger', 'Diğer')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
