# Generated by Django 3.1.12 on 2025-05-27 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0002_event_user'),
        ('randevu', '0002_auto_20250527_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etkinlik.event'),
        ),
    ]
