# Generated by Django 3.1.12 on 2025-05-27 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('randevu', '0003_appointment_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='event',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
